// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeMxzZQY482_u3GhmK3u7-ktYrTU5gQyQ',
    appId: '1:629600632673:web:291888c8f3fb1fdc234f20',
    messagingSenderId: '629600632673',
    projectId: 'platzitripsflutter-9f035',
    authDomain: 'platzitripsflutter-9f035.firebaseapp.com',
    storageBucket: 'platzitripsflutter-9f035.appspot.com',
    measurementId: 'G-HBL162P73H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDAFLomU8wdovSWf4uD1ekX7hlvwinkmlU',
    appId: '1:629600632673:android:5bf27b3acbd1ae58234f20',
    messagingSenderId: '629600632673',
    projectId: 'platzitripsflutter-9f035',
    storageBucket: 'platzitripsflutter-9f035.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGmfMfZ8zteiCjAtcrmWFUefmBgVxFbTI',
    appId: '1:629600632673:ios:5907173b9911712b234f20',
    messagingSenderId: '629600632673',
    projectId: 'platzitripsflutter-9f035',
    storageBucket: 'platzitripsflutter-9f035.appspot.com',
    androidClientId: '629600632673-nb1p221nekd689vfuu7b9hhjvfrp64i4.apps.googleusercontent.com',
    iosClientId: '629600632673-9bp3pvd82j68rtlfenl4dnbgboq5ehmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGmfMfZ8zteiCjAtcrmWFUefmBgVxFbTI',
    appId: '1:629600632673:ios:5907173b9911712b234f20',
    messagingSenderId: '629600632673',
    projectId: 'platzitripsflutter-9f035',
    storageBucket: 'platzitripsflutter-9f035.appspot.com',
    androidClientId: '629600632673-nb1p221nekd689vfuu7b9hhjvfrp64i4.apps.googleusercontent.com',
    iosClientId: '629600632673-9bp3pvd82j68rtlfenl4dnbgboq5ehmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
